
const TOOLBAR_HEIGHT = 24;
const TOOLBAR_BUTTON_SIZE = 24;

const DIRECTION_UP = 0;
const DIRECTION_RIGHT = 1;
const DIRECTION_DOWN = 2;
const DIRECTION_LEFT = 3;

const SPRITE_WIDTH = 16;
const SPRITE_HEIGHT = 16;

const ATTACK_COUNT = 18;

const ENTITY_TYPE_PLAYER = 0;
const ENTITY_TYPE_ALIEN = 1;
const ENTITY_TYPE_BLASTER = 2;
const ENTITY_TYPE_BLUE_KEYCARD = 3;
const ENTITY_TYPE_RADIO = 4;

const ENTITY_SPRITE_OFFSET_X = [0, 0, 16, 17, 23];
const ENTITY_SPRITE_OFFSET_Y = [1, 5, 28, 23, 27];
const DIRECTION_OFFSET_X = [2, 0, 1, 3];
