
const TOOLBAR_HEIGHT = 24;
const TOOLBAR_BUTTON_SIZE = 24;

const DIRECTION_UP = 0;
const DIRECTION_RIGHT = 1;
const DIRECTION_DOWN = 2;
const DIRECTION_LEFT = 3;
const DIRECTION_OFFSET_X = [2, 0, 1, 3];

const SPRITE_WIDTH = 16;
const SPRITE_HEIGHT = 16;

const ATTACK_COUNT = 18;
